In [1]:
import numpy as np
from sympy.physics.wigner import wigner_3j,wigner_6j
import sympy as sy
from numpy import linalg as LA
from IPython.display import Latex,display
import matplotlib.pyplot as plt
# import seaborn as sns
# sns.set()
# sns.set_palette('terrain')
from YbOH_Energy_Levels_symbolic import YbOHLevels
np.set_printoptions(precision=5, suppress=True)

In [2]:
%matplotlib qt

In [3]:
X000_173= YbOHLevels.initialize_state('173','X000',[0,1,2,3],M_values='none',I=[5/2,1/2])

Cannot construct decoupled basis without M values


In [4]:
A000_173= YbOHLevels.initialize_state('173','A000',[1,2,3,4],M_values='none',I=[5/2,1/2])

Cannot construct decoupled basis without M values


In [5]:
A000_173.eigensystem(0.0,0.0);
X000_173.eigensystem(0.0,0.0);

In [6]:
X000_173.evals0/29979.2458

array([-0.07889, -0.0788 ,  0.10964,  0.10971,  0.39419,  0.39428,
        0.41633,  0.41642,  0.42752,  0.4276 ,  0.5854 ,  0.58546,
        0.60536,  0.60542,  0.61382,  0.61387,  1.3794 ,  1.37948,
        1.38479,  1.38486,  1.39854,  1.39863,  1.40023,  1.40029,
        1.41658,  1.41665,  1.5692 ,  1.56924,  1.57585,  1.57587,
        1.58904,  1.5891 ,  1.5898 ,  1.58981,  1.59971,  2.85261,
        2.85269,  2.8529 ,  2.85296,  2.86244,  2.86248,  2.86988,
        2.86996,  2.87527,  2.87529,  2.88671,  2.88673,  2.89336,
        3.0424 ,  3.04244,  3.04379,  3.04381,  3.05446,  3.05447,
        3.0622 ,  3.06226,  3.06602,  3.06606])

In [7]:
A000_173.evals0/29979.2458

array([0.26158, 0.26158, 0.2753 , 0.2753 , 0.5745 , 0.5745 , 0.5854 ,
       0.5854 , 0.64977, 0.64977, 0.87177, 0.87177, 0.95058, 0.95058,
       0.95231, 0.95231, 1.51587, 1.51587, 1.57899, 1.57899, 1.66421,
       1.66421, 1.66656, 1.70174, 1.70174, 1.76982, 1.76982, 1.77415,
       1.77415, 1.8617 , 1.8617 , 1.95912, 1.95912, 2.02142, 2.02142,
       2.98193, 3.00318, 3.00318, 3.04605, 3.04605, 3.11134, 3.11134,
       3.20055, 3.20055, 3.22697, 3.22697, 3.26897, 3.26897, 3.31701,
       3.31701, 3.33013, 3.33013, 3.40782, 3.40782, 3.49722, 3.49722,
       3.58513, 3.58513, 4.97768, 4.97768, 5.01173, 5.01173, 5.06325,
       5.06325, 5.13281, 5.13281, 5.22136, 5.22136, 5.28857, 5.28857,
       5.33054, 5.33054, 5.33553, 5.33553, 5.39696, 5.39696, 5.47165,
       5.47165, 5.55757, 5.55757, 5.65082, 5.65082, 7.4785 , 7.4785 ,
       7.52247, 7.52247, 7.581  , 7.581  , 7.65403, 7.65403, 7.74143,
       7.74143, 7.8431 , 7.8431 ])

In [20]:
from YbOH_Energy_Levels_symbolic import XA_branching_ratios

In [21]:
BR0 = XA_branching_ratios(X000_173,A000_173,0,0.0)

Successfully converted eigenvectors from bBS to aBJ


In [22]:
BR0=

array([[0.38468, 0.04976, 0.03573, ..., 0.     , 0.     , 0.     ],
       [0.00323, 0.3769 , 0.145  , ..., 0.     , 0.     , 0.     ],
       [0.01924, 0.22565, 0.44785, ..., 0.     , 0.     , 0.     ],
       ...,
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ]])

In [23]:
(y,x) = BR0.shape
h=10
fsize = (h,h*x/y)
fig,axes = plt.subplots(1,2,figsize=(9,5),sharey=True,constrained_layout=True)
axes[0].matshow(BR0)
for ax in axes:
    ax.grid(False)

In [67]:
def gen_state_str(vector,q_numbers,label_q,thresh=0.02,show_coeff=True):
    full_label = r''
    nonzero_idx = np.nonzero(vector)[0]
    first = 0
    for i,index in enumerate(nonzero_idx):
        coeff = vector[index]
        if abs(coeff) < thresh:
            first+=1
            continue
        sign = {True: '+', False: '-'}[coeff > 0]
        sign0 = {True: ' ', False: sign}[sign=='+']
        if show_coeff:
            label_str = r'${}{}|'.format({True: sign0, False: sign}[i==first],abs(coeff))
        else:
            label_str = r'${}|'.format({True: sign0, False: sign}[i==first])
        val = {q:q_numbers[q][index] for q in label_q}
        for q in label_q:
            _q = {True: '\u039B', False: q}[q=='L']
            _q = {True: '\u03A3', False: _q}[q=='Sigma']
            _q = {True: '\u03A9', False: _q}[q=='Omega']
            if (abs(val[q]) % 1) !=0:
                label_str+=r'{}=\frac{{{}}}{{{}}},'.format(_q,*val[q].as_integer_ratio())
            else:
                label_str+=r'{}={},'.format(_q,int(val[q]))
        label_str = label_str[:-1]+r'\rangle$'
        full_label+=label_str
    if i==first and show_coeff==False:
        full_label = r'$'+full_label[2:]
    return full_label

In [78]:
fig,ax = plt.subplots(figsize=(10,20),constrained_layout=True)
# ax.set_aspect('equal')
mat = ax.matshow(BR0[:57,:10],cmap=plt.get_cmap('hot'))
y = np.arange(0,len(X000_173.evecs0[:57]))
x = np.arange(0,len(A000_173.evecs0[:10]))
ax.set_yticks(y)
ax.set_xticks(x)
y_labels = [gen_state_str(X000_173.evecs0[i],X000_173.q_numbers,[q for q in X000_173.q_str if (q=='N' or q=='G')],thresh=0.2,show_coeff=False) for i in range(y.size)]
x_labels = [gen_state_str(A000_173.evecs0[i],A000_173.q_numbers,[q for q in A000_173.q_str if (q=='L' or q=='J')],thresh=0.2,show_coeff=False) for i in range(x.size)]
ax.set_yticklabels(y_labels, rotation='40', fontsize=12, ha='right')
ax.set_xticklabels(x_labels, rotation='40', fontsize=12,ha='left')
ax.tick_params(axis='both',labelsize=10,direction='out')
ax.grid(True,which='major',color='white',ls='--',linewidth=0.5)
ax.grid(False,which='minor')
(bot,top) = ax.get_ylim()
#ax.set_ylim(bot+0.5, top-0.5)
cbar = fig.colorbar(mat, ax=ax,fraction=0.015, pad=0.05)
# cbar.set_clim([0,1]);
# ax.set_xlim(-0.5,x.size+0.5);

In [59]:
BRnorm = BR0/BR0.sum(axis=0,keepdims=1)

In [60]:
BRnorm[35:57].sum(axis=0)

array([0.     , 0.     , 0.     , 0.     , 0.15914, 0.16084, 0.11201,
       0.11226, 0.21876, 0.23778, 0.13678, 0.14221, 0.29326, 0.31242,
       0.18851, 0.18777, 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.79851, 0.58875, 0.61849, 0.80528, 0.80529, 0.82262, 0.79898,
       0.81596, 0.8138 , 0.94176, 0.86998, 0.98774, 0.98774, 0.82072,
       0.8177 , 0.98114, 0.97659, 0.97335, 0.96896, 0.96885, 0.96932,
       1.     , 1.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ])

In [31]:
def select_N(N,state):
    idx = []
    N = np.array(N)
    for i,qN in enumerate(state.q_numbers['N']):
        for _N in N:
            if qN == _N:
                idx.append(i)
    return np.array(idx)

def select_J(J,state):
    idx = []
    J = np.array(J)
    for i,qJ in enumerate(state.q_numbers['J']):
        for _J in J:
            if qJ == _J:
                idx.append(i)
    return np.array(idx)

In [61]:
J_idx = select_J([0.5],A000_173)
print(J_idx)
N_idx = select_N([1,3],X000_173)
print(N_idx)

[0 1 2 3 4 5 6 7]
[ 4  5  6  7  8  9 10 11 12 13 14 15 35 36 37 38 39 40 41 42 43 44 45 46
 47 48 49 50 51 52 53 54 55 56 57]


In [58]:
for i in J_idx:
    display(Latex(A000_173.gen_state_str(i,basis=None,label_q=None,thresh=0.001,show_coeff=True,new_line=False,round=None)))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [62]:
for i in N_idx:
    display(Latex(X000_173.gen_state_str(i,basis=None,label_q=None,thresh=0.001,show_coeff=True,new_line=False,round=None)))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>