In [1]:
from config_path import add_to_sys_path
add_to_sys_path()  # Call the function to add path

import numpy as np
from sympy.physics.wigner import wigner_3j,wigner_6j
import sympy as sy
from numpy import linalg as LA
from IPython.display import Latex,display
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()
sns.set_palette('terrain')
from molecular_structure import MoleculeLevels
np.set_printoptions(precision=5, suppress=True)
from energy_levels import branching_ratios, calculate_TDMs

%matplotlib qt

In [6]:
X000= MoleculeLevels.initialize_state('CaOH','40','X000',N_range=[1],I=[0,1/2],S=1/2,round=8, M_values = 'all',M_range=None)

No P values provided, using P=1/2 as default


In [83]:
Bz = np.linspace(1e-6,50,1000)
Ez = np.linspace(0.0,200,1000)

In [71]:
X000.ZeemanMap(Bz,plot=True)

In [92]:
A000= MoleculeLevels.initialize_state('YbOH','174','A000',[1,2],M_values = 'all',I=[0,1/2],S=1/2,round=8,M_range=None,P_values=[1/2])

In [ ]:
N_list = [1]
print(N_list)

In [ ]:
A000= MoleculeLevels.initialize_state('CaOH','40','A000',[1,2],M_values = 'custom',I=[0,1/2],S=1/2,round=8,M_range=[0],P_values=[1/2,3/2])

In [60]:
Bz = np.linspace(1e-6,100,3000)
Ez = np.linspace(0.0,100,5000)

In [78]:
A000.ZeemanMap(Bz,0,plot=True)

In [5]:
A000.eigensystem(1000,0)
M_idx = A000.select_q({'M':[0],'P':[3/2,-3/2]})
print(M_idx)
print('\n')
for i in M_idx:
    display(Latex('$E = '+str(np.round(A000.evals0[i],4))+r'\:\mathrm{MHz}$'))
    print('Decoupled:')
    display(Latex(A000.gen_state_str(i,basis='decoupled',thresh=0.01,label_q=['K','M_N','M_S','M_I','M_F'],round=4)))
    print('Decoupled with J:')
    display(Latex(A000.gen_state_str(i,basis='recoupled_J',thresh=0.01,label_q=['K','N','J','M_J','M_I','M_F'],round=4)))
    print('Case B:')
    display(Latex(A000.gen_state_str(i,basis='bBJ',thresh=0.01,label_q=['K','N','J','F','M'],round=4)))
    print('Case A:')
    display(Latex(A000.gen_state_str(i,thresh=0.01,label_q=['P','K','Sigma','J','F','M'],round=4)))
    print('\n')

[12 13 14 15 16 17 18 19]




<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Decoupled with J:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Decoupled with J:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Decoupled with J:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Decoupled with J:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Decoupled with J:


IndexError: list index out of range

In [5]:
X010= MoleculeLevels.initialize_state('CaOH','40','X010',[1],M_values = 'all',I=[0,1/2],S=1/2,round=8)

In [17]:
X010.eigensystem(1000,1e-7)
M0_idx = X010.select_q({'M':[0]})
print(M0_idx)
print('\n')
for i in M0_idx:
    display(Latex('$E = '+str(np.round(X010.evals0[i],4))+r'\:\mathrm{MHz}$'))
    print('Decoupled:')
    display(Latex(X010.gen_state_str(i,basis='decoupled',thresh=0.01,label_q=['K','M_N','M_S','M_I','M_F'],round=4)))
    print('Case A:')
    display(Latex(X010.gen_state_str(i,basis='aBJ',thresh=0.01,label_q=['K','Sigma','P','M'],round=4)))
    print('Case B:')
    display(Latex(X010.gen_state_str(i,thresh=0.01,round=4)))
    print('\n')

[ 2  3  8 11 12 15 18 19]




<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

Case B:


<IPython.core.display.Latex object>

In [22]:
A000.display_levels(1000,1e-7,'F',idx=M_idx)

In [29]:
BR = branching_ratios(X000,A000,0,30)

Successfully converted eigenvectors from bBJ to aBJ


In [54]:
def l2s(inputlist):
      """
      Convert a flatten list to a list of slices:
      test = [0,2,3,4,5,6,12,99,100,101,102,13,14,18,19,20,25]
      l2s(test)
      -> [(0, 0), (2, 6), (12, 14), (18, 20), (25, 25), (99, 102)]
      """
      inputlist.sort()
      pointers = np.where(np.diff(inputlist) > 1)[0]
      pointers = zip(np.r_[0, pointers+1], np.r_[pointers, len(inputlist)-1])
      slices = [slice(inputlist[i], inputlist[j]+1) for i, j in pointers]
      return slices

In [55]:
gs

(0, 11)

In [56]:
BR[slice(0,11),:].shape

(11, 24)

In [70]:
fig,ax = plt.subplots(figsize=(10,10),constrained_layout=True)
e_state = A000
g_state = X000
gidx = X000.select_q({'N':1},parity='-')
eidx = A000.select_q({'J':0.5},parity='+')
gs = l2s(gidx)[0]
es = l2s(eidx)[0]
log=False
BR_plot = BR 
if log:
    BR_plot=np.log10(BR_plot)
    vmin = -10
    vmax = 0
else:
    vmin=None
    vmax = None
#     log_BR = np.copy(BR0)
#     for i,val1 in enumerate(log_BR):
#         for j,val2 in enumerate(val1):
#             if val2 !=0:
#                 log_BR[i,j] = np.log10(val2)
#     BR_plot = log_BR
if log:
    mat = ax.matshow(BR_plot[gs,es],cmap=plt.get_cmap('viridis'),norm=Lognorm())
else: 
    mat = ax.matshow(BR_plot[gs,es],cmap=plt.get_cmap('viridis'),vmax=1,vmin=0)
x = np.arange(0,len(eidx))
y = np.arange(0,len(gidx))
ax.set_yticks(y)
ax.set_xticks(x)
x_labels = [e_state.gen_state_str(i,thresh=0.2,single=True,parity=True,show_coeff=False, label_q=['F','J','M']) for i in eidx]
y_labels = [g_state.gen_state_str(i,thresh=0.2,single=True,parity=True,show_coeff=False, label_q=['F','J','M']) for i in gidx]
# x_labels = [X010.gen_state_str(i,thresh=0.3,single=True,parity=False,show_coeff=True, basis='decoupled',label_q=['K','M_N','M_S','M_F'],round=2) for i in N2]
# y_labels = [X010.gen_state_str(i,thresh=0.3,single=True,parity=False,show_coeff=True, basis='decoupled',label_q=['K','M_N','M_S','M_F'],round=2) for i in N1]
ax.set_yticklabels(y_labels, rotation='40', fontsize=12, ha='right')
ax.set_xticklabels(x_labels, rotation='40', fontsize=12,ha='left')
ax.tick_params(axis='both',labelsize=10,direction='out')
ax.grid(True,which='major',color='white',ls='--',linewidth=0.5)
ax.grid(False,which='minor')
(bot,top) = ax.get_ylim()
# ax.set_ylim(bot+0.5, top-0.5)
cbar = fig.colorbar(mat, ax=ax,fraction=0.015, pad=0.05)
cbar.set_label(label='BR',size=16)
#ax.set_xlim(-0.5,x.size+0.5);

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:42: MatplotlibDeprecationWarning: Auto-removal of grids by pcolor() and pcolormesh() is deprecated since 3.5 and will be removed two minor releases later; please call grid(False) first.


In [96]:
X000.display_levels(0,15,idx=gidx, pattern_q = 'F',parity=True)

In [93]:
A000.display_levels(0,0,idx = A000.select_q({'J':[0.5,1.5]}),pattern_q = 'F',parity=True)

In [82]:
A000.display_levels(0,30,idx=eidx, pattern_q = 'F',parity=True)

In [86]:
A000.ZeemanMap(Bz,0,plot=True)

In [85]:
state = A000
idx = eidx
field = Bz
state.ZeemanMap(field,0,plot=False)
plt.figure(figsize=(10,7))
for (i,trace) in enumerate(state.evals_B.T[idx]):
    plt.plot(field,trace)
plt.xlabel('B (G)',fontsize=14)
plt.ylabel('Energy (MHz)',fontsize=14)
plt.title(r'$^{40}$CaOH $\tilde{A}(000)$ Zeeman Shifts, $N=1$',fontsize=16);

plt.figure(figsize=(10,7))
for (i,trace) in enumerate(state.evals_B.T[idx]):
    grad = np.gradient(trace)/(field[1]-field[0])
    plt.plot(field,grad)
plt.xlabel('B (G)',fontsize=14)
plt.ylabel('Magnetization',fontsize=14)
plt.title(r'$^{40}$CaOH $\tilde{A}(000)$ Polarization, $N=1$',fontsize=16);

In [76]:
A000.eigensystem(0,30)
print('\n')
for i in eidx:
    display(Latex('$E = '+str(np.round(A000.evals0[i],4))+r'\:\mathrm{MHz}$'))
    print('Decoupled:')
    display(Latex(A000.gen_state_str(i,basis='decoupled',thresh=0.01,label_q=['K','M_N','M_S','M_I','M_F'],round=4)))
#     print('Case B:')
#     display(Latex(A000.gen_state_str(i,basis='bBJ',thresh=0.01,label_q=['K','N','J','F','M'],round=4)))
    print('Case A:')
    display(Latex(A000.gen_state_str(i,thresh=0.01,label_q=['P','K','Sigma','J','F','M'],round=4)))
    print('\n')

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

Decoupled:


<IPython.core.display.Latex object>

Case A:


<IPython.core.display.Latex object>

In [ ]:
A000.eigensystem(0,30)
print('\n')
for i in [3,4]:
    display(Latex('$E = '+str(np.round(A000.evals0[i],4))+r'\:\mathrm{MHz}$'))
    print('Decoupled:')
    display(Latex(A000.gen_state_str(i,basis='decoupled',thresh=0.01,label_q=['K','M_N','M_S','M_I','M_F'],round=4)))
#     print('Case B:')
#     display(Latex(A000.gen_state_str(i,basis='bBJ',thresh=0.01,label_q=['K','N','J','F','M'],round=4)))
    print('Case A:')
    display(Latex(A000.gen_state_str(i,thresh=0.01,label_q=['P','K','Sigma','J','F','M'],round=4)))
    print('\n')

In [34]:
fig,ax = plt.subplots(figsize=(10,10),constrained_layout=True)
mat = ax.matshow(TDM_0,cmap=plt.get_cmap('magma'))
cbar = fig.colorbar(mat, ax=ax,fraction=0.015, pad=0.05)
ax.grid(False)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: MatplotlibDeprecationWarning: Auto-removal of grids by pcolor() and pcolormesh() is deprecated since 3.5 and will be removed two minor releases later; please call grid(False) first.
  This is separate from the ipykernel package so we can avoid doing imports until


In [28]:
X010.select_q({'M':0})

array([ 2,  3,  8, 11, 12, 15, 18, 19])

In [30]:
slice(B000.select_q({'M':0}))

slice(None, array([0, 2]), None)

In [32]:
TDM_0[np.ix_(X010.select_q({'M':1}),B000.select_q({'M':1}))]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [18]:
B0_idx = B000.select_q({'M':[0]})
X1_idx = 