In [1]:
from config_path import add_to_sys_path
add_to_sys_path()  # Call the function to add path

import numpy as np
from sympy.physics.wigner import wigner_3j,wigner_6j
import sympy as sy
from numpy import linalg as LA
from IPython.display import Latex,display
import matplotlib.pyplot as plt
# import seaborn as sns
# sns.set()
# sns.set_palette('terrain')
from YbOH_energy_levels_symbolic import YbOHLevels
from YbOH_energy_levels_symbolic import xa_branching_ratios
np.set_printoptions(precision=5, suppress=True)

In [2]:
%matplotlib qt

In [3]:
X000_174= YbOHLevels.initialize_state('174','X000',[0,1,2],M_values='all',I=[0,1/2])

In [4]:
A000_174= YbOHLevels.initialize_state('174','A000',[1],M_values='all',I=[0,1/2])

In [23]:
Bz=np.linspace(1e-6,0.1,3000)

In [24]:
X000_174.ZeemanMap(Bz,0,plot=True)
plt.ylim(14650,14660)
X000_174.ZeemanMap(Bz,0,plot=True)
plt.ylim(14770,14785)

(14770, 14785)

In [25]:
A000_174.ZeemanMap(Bz,0,plot=True)

In [26]:
plt.figure(figsize=(10,5))
for (i,trace) in enumerate(A000_174.evals_B.T[:4]):
    A000_174.write_state(i,0,0.016)
    plt.plot(Bz,trace)
    print('\n')
plt.show()

E = 8606.08528594614 MHz

 -0.66897 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=0.0,M=0.0> 

 -0.66897 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=0.0,M=0.0> 

 -0.22908 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=1.0,M=0.0> 

 -0.22908 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=1.0,M=0.0> 



E = 8606.097701142968 MHz

 -0.70711 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=1.0,M=1.0> 

 -0.70711 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=1.0,M=1.0> 



E = 8606.106380716357 MHz

 0.22908 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=0.0,M=0.0> 

 0.22908 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=0.0,M=0.0> 

 -0.66897 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=1.0,M=0.0> 

 -0.66897 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=1.0,M=0.0> 



E = 8606.110632182908 MHz

 -0.70711 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=1.0,M=-1.0> 

 -0.70711 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=1.0,M=-1.0> 





In [27]:
plt.figure(figsize=(10,5))
for (i,trace) in enumerate(X000_174.evals_B.T[:4]):
    X000_174.write_state(i,0,0.016)
    plt.plot(Bz,trace)
    print('\n')
plt.show()

E = 14654.295619542896 MHz

 -0.01979 |Λ=0,N=1,J=0.5,F=1.0,M=-1.0> 

 0.9998 |Λ=0,N=1,J=1.5,F=1.0,M=-1.0> 

 -0.00225 |Λ=0,N=1,J=1.5,F=2.0,M=-1.0> 



E = 14654.313864430407 MHz

 0.00017 |Λ=0,N=1,J=0.5,F=0.0,M=0.0> 

 -0.01988 |Λ=0,N=1,J=0.5,F=1.0,M=0.0> 

 0.9998 |Λ=0,N=1,J=1.5,F=1.0,M=0.0> 

 -0.0026 |Λ=0,N=1,J=1.5,F=2.0,M=0.0> 



E = 14654.332124709179 MHz

 0.01997 |Λ=0,N=1,J=0.5,F=1.0,M=1.0> 

 -0.9998 |Λ=0,N=1,J=1.5,F=1.0,M=1.0> 

 0.00226 |Λ=0,N=1,J=1.5,F=2.0,M=1.0> 



E = 14657.321640255002 MHz

 1.0 |Λ=0,N=1,J=1.5,F=2.0,M=-2.0> 





In [28]:
plt.figure(figsize=(10,5))
deltaB = Bz[1]-Bz[0]
for (i,trace) in enumerate(A000_174.evals_B.T[:4]):
    A000_174.write_state(i,0,0.1)
    grad = np.gradient(trace)
    print('gfactor =',grad[0]/deltaB/1.399624494)
    plt.plot(Bz,grad/deltaB)
    print('\n')
plt.show()

E = 8606.05457351611 MHz

 -0.54817 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=0.0,M=0.0> 

 -0.54817 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=0.0,M=0.0> 

 -0.44666 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=1.0,M=0.0> 

 -0.44666 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=1.0,M=0.0> 

gfactor = -0.00024629057858788965


E = 8606.063757144599 MHz

 0.70711 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=1.0,M=1.0> 

 0.70711 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=1.0,M=1.0> 

gfactor = -0.28871651804162046


E = 8606.13709310918 MHz

 0.44666 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=0.0,M=0.0> 

 0.44666 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=0.0,M=0.0> 

 -0.54817 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=1.0,M=0.0> 

 -0.54817 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=1.0,M=0.0> 

gfactor = 0.0002474598644492026


E = 8606.144576144121 MHz

 -0.70711 |Λ=1,Σ=-0.5,Ω=0.5,J=0.5,F=1.0,M=-1.0> 

 -0.70711 |Λ=-1,Σ=0.5,Ω=-0.5,J=0.5,F=1.0,M=-1.0> 

gfactor = 0.2887162841844482




In [84]:
def gF(N,J,F,I=1/2,S=1/2):
    if F==0:
        return 0
    else:
        return 2*(J*(J+1)-N*(N+1)+S*(S+1))/(2*J*(J+1))*(F*(F+1)-I*(I+1)+J*(J+1))/(2*F*(F+1))

In [95]:
gF(1,1/2,1)

-0.3333333333333333

In [79]:
BR0 = xa_branching_ratios(X000_174,A000_174,0,16e-3)

Successfully converted eigenvectors from bBJ to aBJ


In [5]:
BR0 = xa_branching_ratios(X000_174,A000_174,0,1000)
#BR_field = xa_branching_ratios(X000_174,A000_174,100,0.35)

Successfully converted eigenvectors from bBJ to aBJ


In [6]:
(y,x) = BR0.shape
h=10
fsize = (h,h*x/y)

In [7]:
fig,axes = plt.subplots(1,2,figsize=(9,5),sharey=True,constrained_layout=True)
axes[0].matshow(BR0)
#axes[1].matshow(BR_field)
for ax in axes:
    ax.grid(False)

In [8]:
def gen_state_str(vector,q_numbers,label_q,thresh=0.02,show_coeff=True):
    full_label = r''
    nonzero_idx = np.nonzero(vector)[0]
    first = 0
    for i,index in enumerate(nonzero_idx):
        coeff = vector[index]
        if abs(coeff) < thresh:
            first+=1
            continue
        sign = {True: '+', False: '-'}[coeff > 0]
        sign0 = {True: ' ', False: sign}[sign=='+']
        if show_coeff:
            label_str = r'${}{}|'.format({True: sign0, False: sign}[i==first],abs(coeff))
        else:
            label_str = r'${}|'.format({True: sign0, False: sign}[i==first])
        val = {q:q_numbers[q][index] for q in label_q}
        for q in label_q:
            _q = {True: '\u039B', False: q}[q=='L']
            _q = {True: '\u03A3', False: _q}[q=='Sigma']
            _q = {True: '\u03A9', False: _q}[q=='Omega']
            if (abs(val[q]) % 1) !=0:
                label_str+=r'{}=\frac{{{}}}{{{}}},'.format(_q,*val[q].as_integer_ratio())
            else:
                label_str+=r'{}={},'.format(_q,int(val[q]))
        label_str = label_str[:-1]+r'\rangle$'
        full_label+=label_str
    if i==first and show_coeff==False:
        full_label = r'$'+full_label[2:]
    return full_label

In [10]:
fig,ax = plt.subplots(figsize=(15,15),constrained_layout=True)
# ax.set_aspect('equal')
mat = ax.matshow(BR0,cmap=plt.get_cmap('hot'))
y = np.arange(0,len(X000_174.evecs0))
x = np.arange(0,len(A000_174.evecs0))
ax.set_yticks(y)
ax.set_xticks(x)
y_labels = [gen_state_str(X000_174.evecs0[i],X000_174.q_numbers,[q for q in X000_174.q_str if (q=='N' or q=='J' or q=='F' or q=='M')],thresh=0.1,show_coeff=True) for i in range(y.size)]
x_labels = [gen_state_str(A000_174.evecs0[i],A000_174.q_numbers,[q for q in A000_174.q_str if (q=='J' or q=='F' or q=='M')],thresh=0.1,show_coeff=True) for i in range(x.size)]
ax.set_yticklabels(y_labels, rotation='30', fontsize=10, ha='right')
ax.set_xticklabels(x_labels, rotation='30', fontsize=10,ha='left')
ax.tick_params(axis='both',labelsize=10,direction='out')
ax.grid(True,which='major',color='white',ls='--',linewidth=0.5)
ax.grid(False,which='minor')
(bot,top) = ax.get_ylim()
ax.set_ylim(bot+0.5, top-0.5)
cbar = fig.colorbar(mat, ax=ax,fraction=0.015, pad=0.05)
# cbar.set_clim([0,1]);
# ax.set_xlim(-0.5,x.size+0.5);

In [137]:
a = np.arange(12).reshape(4,3)
a.sum(axis=0)

array([18, 22, 26])

In [34]:
BR0.sum(axis=0)

array([0.99994, 0.99996, 0.99996, 0.99994, 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.69999, 0.70001, 0.70007, 0.70007, 0.70005,
       0.70006, 0.7    , 0.70001])

In [70]:
(BR0[:,0]+BR0[:,2])/2

array([0.     , 0.     , 0.     , 0.     , 0.06806, 0.05245, 0.06782,
       0.     , 0.04157, 0.05556, 0.04176, 0.     , 0.22375, 0.11421,
       0.22369, 0.11111])

In [ ]:
(BR0[:,0]+BR0[:,2])/2

In [62]:
(BR0[:,4]+BR0[:,6])/2

array([0.11111, 0.22222, 0.11111, 0.22222, 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     ])

In [75]:
BR0[:,-8]

array([0.     , 0.     , 0.     , 0.     , 0.24446, 0.1755 , 0.     ,
       0.01844, 0.04893, 0.04006, 0.     , 0.     , 0.     , 0.05275,
       0.01163, 0.10824])

In [76]:
(BR0[:,-3]+BR0[:,-6])/2

array([0.     , 0.     , 0.     , 0.     , 0.11421, 0.01904, 0.11433,
       0.     , 0.13341, 0.01778, 0.13325, 0.     , 0.02908, 0.05429,
       0.02904, 0.05555])

In [77]:
(BR0[:,-11]+BR0[:,-14])/2

array([0.05556, 0.02778, 0.05556, 0.02778, 0.     , 0.     , 0.     ,
       0.     , 0.     , 0.     , 0.     , 0.     , 0.     , 0.     ,
       0.     , 0.     ])

In [30]:
BR0.sum(axis=1)

array([0.7    , 0.70001, 0.79715, 0.79713, 0.89707, 0.89708, 0.7    ,
       0.70001, 0.80292, 0.80295, 0.90287, 0.90286])

In [13]:
BRnorm = BR0/BR0.sum(axis=0,keepdims=1)

In [39]:
BR0[:,4]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

C:\Users\ajadbaba\Anaconda3\lib\site-packages\ipykernel\eventloops.py:106: UserWarning: constrained_layout not applied because axes sizes collapsed to zero.  Try making figure larger or axes decorations smaller.
  app.exec_()
C:\Users\ajadbaba\Anaconda3\lib\site-packages\ipykernel\eventloops.py:106: UserWarning: constrained_layout not applied because axes sizes collapsed to zero.  Try making figure larger or axes decorations smaller.
  app.exec_()


In [15]:
BRnorm

array([[0.     , 0.     , 0.     , 0.22222, 0.11111, 0.     , 0.     ,
        0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.66666, 0.44445, 0.05555, 0.16667, 0.     ,
        0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.31473, 0.06196, 0.     , 0.     , 0.     , 0.     , 0.62578,
        0.08161, 0.89964, 0.     , 0.     , 0.     ],
       [0.     , 0.27778, 0.     , 0.     , 0.     , 0.     , 0.12698,
        0.68571, 0.1    , 1.     , 0.     , 0.     ],
       [0.68527, 0.43805, 0.     , 0.     , 0.     , 0.     , 0.08851,
        0.23268, 0.00036, 0.     , 0.     , 0.     ],
       [0.     , 0.22222, 0.     , 0.     , 0.     , 0.     , 0.15873,
        0.     , 0.     , 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , 0.00004, 0.29588, 0.02252, 0.     ,
        0.     , 0.     , 0.     , 0.66847, 0.03678],
       [0.     , 0.     , 0.     , 0.     , 0.     , 0.28   , 0.     ,
        0.     , 0.     , 0.     , 0.048  , 0.68571],


In [17]:
fig,ax = plt.subplots(figsize=(15,15),constrained_layout=True)
# ax.set_aspect('equal')
mat = ax.matshow(BRnorm,cmap=plt.get_cmap('hot'))
y = np.arange(0,len(X000_174.evecs0))
x = np.arange(0,len(A000_174.evecs0))
ax.set_yticks(y)
ax.set_xticks(x)
y_labels = [gen_state_str(X000_174.evecs0[i],X000_174.q_numbers,[q for q in X000_174.q_str if (q=='N' or q=='J' or q=='F')],thresh=0.02,show_coeff=False) for i in range(y.size)]
x_labels = [gen_state_str(A000_174.evecs0[i],A000_174.q_numbers,[q for q in A000_174.q_str if (q=='L' or q=='J' or q=='F')],thresh=0.02,show_coeff=False) for i in range(x.size)]
ax.set_yticklabels(y_labels, rotation='30', fontsize=8, ha='right')
ax.set_xticklabels(x_labels, rotation='30', fontsize=8,ha='left')
ax.tick_params(axis='both',labelsize=8,direction='out')
ax.grid(True,which='major',color='white',ls='--',linewidth=0.5)
ax.grid(False,which='minor')
(bot,top) = ax.get_ylim()
#ax.set_ylim(bot+0.5, top-0.5)
cbar = fig.colorbar(mat, ax=ax,fraction=0.015, pad=0.05)
# cbar.set_clim([0,1]);
# ax.set_xlim(-0.5,x.size+0.5);

In [161]:
evals, evecs = X000_174.eigensystem(0,1)

In [87]:
display(Latex(gen_state_str(X000_174.evecs0[1],X000_174.q_numbers,X000_174.q_str,show_coeff=False)))

<IPython.core.display.Latex object>

In [83]:
display(Latex(gen_state_str(A000_174.evecs0[6],A000_174.q_numbers,A000_174.q_str,show_coeff=False)))

<IPython.core.display.Latex object>

In [84]:
gen_state_str(X000_174.evecs0[0],X000_174.q_numbers,X000_174.q_str,show_coeff=False)

'$|Λ=0,N=0,J=\\frac{1}{2},F=0,M=0\\rangle$'

In [38]:
print(r'{}$|$${}$={}$\rangle$'.format(1,'F',1))

1$|$$F$=1$\rangle$


In [66]:
from fractions import Fraction

In [70]:
display(Latex(str(Fraction(0.25))))

<IPython.core.display.Latex object>

In [76]:
display(Latex(r'$\frac{}{}$'.format(*(1.0).as_integer_ratio())))

<IPython.core.display.Latex object>

In [86]:
abs(1) % 1

0

In [84]:
-1.0+1.0

0.0

In [21]:
M = self.q_numbers['M'][np.argmax(evec**2)]

In [11]:
ax.set_xticklabels(x_ticks_labels, rotation='vertical', fontsize=18)

array([0., 0., 0., 0.])

In [33]:
for index in np.nonzero(vector)[0]:

(array([    -2.37   ,      0.78859,      0.78999,      0.79139,
         14654.75787,  14654.75903,  14654.76018,  14657.09665,
         14657.09735,  14657.09806,  14657.09876,  14657.09946,
         14777.42764,  14777.42809,  14777.42855,  14779.56106,
         44007.97296,  44007.97361,  44007.97426,  44007.97491,
         44007.97556,  44010.15892,  44010.15939,  44010.15985,
         44010.16032,  44010.16079,  44010.16125,  44010.16172,
         44211.41627,  44211.41668,  44211.4171 ,  44211.41752,
         44211.41794,  44213.32749,  44213.32819,  44213.32889,
         88057.88207,  88057.88252,  88057.88297,  88057.88342,
         88057.88387,  88057.88432,  88057.88477,  88060.00662,
         88060.00697,  88060.00732,  88060.00767,  88060.00802,
         88060.00837,  88060.00872,  88060.00907,  88060.00943,
         88342.3133 ,  88342.31364,  88342.31397,  88342.3143 ,
         88342.31463,  88342.31497,  88342.3153 ,  88344.22343,
         88344.2239 ,  88344.22436,  883

In [17]:
x@u

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
a = np.eye(4,6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [8]:
print(a.T)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
a@a.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
a[3,5] = 2

In [12]:
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 2.]])

In [1]:
True or True

True

In [2]:
max(2,2)

2

In [3]:
range(0)

range(0, 0)

In [14]:
for i in range(2,2):
    print(i)

In [37]:
Lambda=0
print(*[i for i in {True:[0], False:[-Lambda,Lambda]}[Lambda==0]])

0


In [39]:
x=[1,1/2,1/2]

In [40]:
len(x[1:])

2

In [42]:
np.arange(1,3)

array([1, 2])

In [62]:
np

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [58]:
x= np.array([5])

In [59]:
len(x)

1

In [54]:
x is type(x)

False

In [63]:
isinstance(x,np.ndarray)

True

In [64]:
x

array([5])

In [65]:
x = None

In [66]:
x is None

True

In [67]:
x = 5

In [68]:
x is None

False

In [69]:
x = [1,2,3]

In [70]:
len(x)

3

In [71]:
x[len(x)]

IndexError: list index out of range

In [73]:
def count_momenta(J_list, M_values):
    if M_values == 'all':
         num = 1
         for J in J_list:
             num*=(2*J+1)
    else:
        num = iter_count(J_list,M_values,1)
    return num

def iter_count(J_list,M_values,i,J = None):
    J0 = {True:J_list[0], False:J}[J is None]
    Ji = J_list[i]
    n = len(J_list) - i
    if n>1:
        sum = 0
        for Jf in np.arange(abs(J0-Ji),J0+Ji+1,1):
            sum+=iter_count(J_list,M_values,i+1,J=Jf)
        return sum
    else:
        sum=0
        if M_values == 'pos':
            for Jf in np.arange(abs(J0-Ji),J0+Ji+1,1):
                sum+=Jf+1
            return sum
        elif M_values == 'none':
            for Jf in np.arange(abs(J0-Ji),J0+Ji+1,1):
                sum+=1
            return sum

In [96]:
for N in range(10):
    print(count_momenta([N,5/2,5/2], 'pos'))

7.0
21.0
35.0
48.0
60.0
72.0
84.0
96.0
108.0
120.0


In [92]:
print(count_momenta(J,'all'))

252.0


In [93]:
print(count_momenta(J,'pos'))

132.0


In [94]:
print(count_momenta(J,'none'))

12
